// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc4579.T34.subsystems;

import org.usfirst.frc4579.T34.Robot;
import org.usfirst.frc4579.T34.RobotMap;
import org.usfirst.frc4579.T34.commands.*;

import edu.wpi.first.wpilibj.*;
import edu.wpi.first.wpilibj.command.Subsystem;


/**
 *
 */
public class Drivetrain extends Subsystem {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    SpeedController fL_Motor = RobotMap.drivetrainFL_Motor;
    SpeedController fR_Motor = RobotMap.drivetrainFR_Motor;
    SpeedController bL_Motor = RobotMap.drivetrainBL_Motor;
    SpeedController bR_Motor = RobotMap.drivetrainBR_Motor;
    RobotDrive drivebase = RobotMap.drivetrainDrivebase;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    
    // Put methods for controlling this subsystem
    // here. Call these from Commands.

    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
        setDefaultCommand(new Drive());

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
	
        // Set the default command for a subsystem here.
        //setDefaultCommand(new MySpecialCommand());
    }
    
    public void driveManual(double x, double y, double z, double angle) {
    	drivebase.mecanumDrive_Cartesian(x, y, z, angle);
    }
    
    public void stop() {
    	fL_Motor.set(0.0);
    	fR_Motor.set(0.0);
    	bL_Motor.set(0.0);
    	bR_Motor.set(0.0);
    }
}

