// RobotBuilder Version: 1.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.
package org.usfirst.frc4579.T34.subsystems;
import com.RoboEagles4579.filters.FirstOrderLPF;
import org.usfirst.frc4579.T34.RobotMap;
import org.usfirst.frc4579.T34.commands.*;
import edu.wpi.first.wpilibj.*;
import edu.wpi.first.wpilibj.command.Subsystem;
import org.usfirst.frc4579.T34.Robot;
/**
 *
 */
public class driveTrain extends Subsystem {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    SpeedController frontLeft_M = RobotMap.driveTrainfrontLeft_M;
    SpeedController frontRight_M = RobotMap.driveTrainfrontRight_M;
    SpeedController rearLeft_M = RobotMap.driveTrainrearLeft_M;
    SpeedController rearRight_M = RobotMap.driveTrainrearRight_M;
    RobotDrive driveBase = RobotMap.driveTraindriveBase;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    
    FirstOrderLPF xLPF = new FirstOrderLPF(0.25);
    FirstOrderLPF yLPF = new FirstOrderLPF(0.25);
    FirstOrderLPF zLPF = new FirstOrderLPF(0.25);
    
    public void drive(double x, double y, double z) {
        
        x = xLPF.filter(x);
        y = yLPF.filter(y);
        z = zLPF.filter(z);
        
        driveBase.mecanumDrive_Cartesian(x, 
                                         y,
                                         z, 
                                         Robot.measurement.getGyroAngle());
        
    }
    
    public void stop() {
        drive(0,0,0);
    }
        
    // Put methods for controlling this subsystem
    // here. Call these from Commands.
    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
        setDefaultCommand(new driveCmd());
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
	
        // Set the default command for a subsystem here.
        //setDefaultCommand(new MySpecialCommand());
    }
}
