// RobotBuilder Version: 1.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.
package org.usfirst.frc4579.T34.subsystems;
import com.RoboEagles4579.math.Vector3d;
import org.usfirst.frc4579.T34.RobotMap;
import org.usfirst.frc4579.T34.commands.*;
import edu.wpi.first.wpilibj.*;
import edu.wpi.first.wpilibj.command.Subsystem;
/**
 *
 */
public class measurement extends Subsystem {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    Gyro robotGyro = RobotMap.measurementrobotGyro;
    Accelerometer robotAccelerometer = RobotMap.measurementrobotAccelerometer;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    
    //Override robotAcceleromter from RobotBuilder with ADXL345_SPI accelerometer (3-axis)
    ADXL345_SPI robotPrimaryAccelerometer = new ADXL345_SPI(1, 2, ADXL345_SPI.DataFormat_Range.k2G);
    
    //Acceleration in Gs
    Vector3d accelVector = new Vector3d(0.0,0.0,00);
    
    //Gyro angle in degrees
    double gyroAngle = 0.0;
    
    // Put methods for controlling this subsystem
    // here. Call these from Commands.
    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
	
        // Set the default command for a subsystem here.
        //setDefaultCommand(new MySpecialCommand());
    }
    
    public double getGyroAngle() {
        return gyroAngle;
    }
    
    public double getGyroRadians() {
        return getGyroAngle() * (Math.PI / 180);
    }
    
    public Vector3d getAccelVector() {
        return accelVector;
    }
    
    public void initialize() {
        
    }
    
    public void measure() {
        
        accelVector.X = robotPrimaryAccelerometer.getAcceleration(ADXL345_SPI.Axes.kX);
        accelVector.Y = robotPrimaryAccelerometer.getAcceleration(ADXL345_SPI.Axes.kY);
        accelVector.Z = robotPrimaryAccelerometer.getAcceleration(ADXL345_SPI.Axes.kZ);
        gyroAngle = robotGyro.getAngle();
        
    }
    
}
